import { Trans } from 'react-i18next';

export const TAGS = [
  {
    name: 'ReactJS',
    type: 'frontend',
    isFavorite: true,
  },
  {
    name: 'NextJS',
    type: 'frontend',
    isFavorite: true,
  },
  {
    name: 'NodeJS',
    type: 'backend',
    isFavorite: true,
  },
  {
    name: 'MongoDB',
    type: 'data',
    isFavorite: true,
  },
  {
    name: 'JavaScript',
    type: 'frontend',
    isFavorite: false,
  },
  {
    name: 'TypeScript',
    type: 'frontend',
    isFavorite: false,
  },
  {
    name: 'VueJS',
    type: 'frontend',
    isFavorite: false,
  },
  {
    name: 'PHP',
    type: 'backend',
    isFavorite: false,
  },
  {
    name: 'SQL',
    type: 'backend',
    isFavorite: false,
  },
  {
    name: 'AWS',
    type: 'other',
    isFavorite: false,
  },
  {
    name: 'C',
    type: 'backend',
    isFavorite: false,
  },
  {
    name: 'Solidity',
    type: 'blockchain',
    isFavorite: true,
  },
  {
    name: 'NFT',
    type: 'blockchain',
    isFavorite: true,
  },
];

export const PROJECTS = [
  {
    name: 'Maral.fr',
    stack: ['NodeJS', 'MongoDB', 'AWS', 'Stripe'],
    description: <Trans>MaralSmallDescription</Trans>,
    github: 'https://github.com/ablin42/seyrene',
    link: 'https://maral.fr/',
  },
  {
    name: 'Xs-url.fr',
    stack: ['TypeScript', 'NodeJS', 'MongoDB', 'ReactJS'],
    description: <Trans>XsUrlSmallDescription</Trans>,
    github: 'https://github.com/ablin42/url-shortener',
    link: 'http://xs-url.fr/',
  },
  {
    name: 'Printf',
    stack: ['C'],
    description: <Trans>PrintfSmallDescription</Trans>,
    github: 'https://github.com/ablin42/ft_printf',
    link: '',
  },
  {
    name: 'PushSwap',
    stack: ['C'],
    description: <Trans>PushSwapSmallDescription</Trans>,
    github: 'https://github.com/ablin42/push_swap',
    link: '',
  },
  {
    name: 'Wireframe',
    stack: ['C'],
    description: <Trans>WireframeSmallDescription</Trans>,
    github: 'https://github.com/ablin42/Wireframe',
    link: '',
  },
  {
    name: 'GetNextLine',
    stack: ['C'],
    description: <Trans>GetNextLineSmallDescription</Trans>,
    github: 'https://github.com/ablin42/getnextline',
    link: '',
  },
  {
    name: 'Fillit',
    stack: ['C'],
    description: <Trans>FillitSmallDescription</Trans>,
    github: 'https://github.com/ablin42/fillit',
    link: '',
  },
  {
    name: 'Libft',
    stack: ['C'],
    description: <Trans>LibftSmallDescription</Trans>,
    github: 'https://github.com/ablin42/libft',
    link: '',
  },
  {
    name: 'Camagru',
    stack: ['PHP', 'JavaScript', 'SQL'],
    description: <Trans>CamagruSmallDescription</Trans>,
    github: 'https://github.com/ablin42/Camagru',
    link: '',
  },
  {
    name: 'Matcha',
    stack: ['PHP', 'JavaScript', 'SQL', 'VueJS'],
    description: <Trans>MatchaSmallDescription</Trans>,
    github: 'https://github.com/ablin42/matcha',
    link: '',
  },
  {
    name: 'Hypertube',
    stack: ['JavaScript'],
    description: <Trans>HypertubeSmallDescription</Trans>,
    github: 'https://github.com/ablin42/torrent',
    link: '',
  },
  {
    name: 'Flipper',
    stack: ['ReactJS', 'JavaScript'],
    description: <Trans>FlipperSmallDescription</Trans>,
    github: 'https://github.com/ablin42/flipper',
    link: '',
  },
  {
    name: 'TokenizedVotes',
    stack: ['Solidity', 'JavaScript', 'TypeScript'],
    description: <Trans>TokenizedSmallVotesDescription</Trans>,
    github: 'https://github.com/ablin42/HARBTEAM-08-Tokenized-Votes',
    link: '',
  },
  {
    name: 'Chaproulette.lol',
    stack: ['NextJS', 'ReactJS', 'JavaScript', 'TypeScript'],
    description: <Trans>ChaprouletteSmallDescription</Trans>,
    github: 'https://github.com/ablin42/chaproulette',
    link: 'https://chaproulette.lol/',
  },
  {
    name: 'BullvsBear API',
    stack: ['NodeJS', 'JavaScript', 'MongoDB'],
    description: <Trans>BullvsBearAPISmallDescription</Trans>,
    github: 'https://github.com/ablin42/prediction-api/blob/master/package.json',
    link: 'https://pcs-prediction-api.herokuapp.com/',
  },
  {
    name: 'BullvsBear Scraping',
    stack: ['NodeJS', 'JavaScript', 'MongoDB', 'Puppeteer'],
    description: <Trans>BullvsBearScrapingSmallDescription</Trans>,
    github: 'https://github.com/ablin42/prediction-scraping',
    link: '',
  },
  {
    name: 'BullvsBear',
    stack: ['ReactJS', 'NextJS', 'JavaScript'],
    description: <Trans>BullvsBearSmallDescription</Trans>,
    github: 'https://github.com/ablin42/bullvsbear',
    link: 'https://www.bullvsbear.pro/',
  },
  {
    name: 'Dungeon Defenders',
    stack: ['Solidity', 'ReactJS', 'TypeScript', 'NFT', 'NodeJS'],
    description: <Trans>DungeonDefendersSmallDescription</Trans>,
    github: 'https://github.com/ablin42/dungeon-defenders',
    link: 'https://dungeondefenders.xyz/',
  },
  {
    name: 'ablin.dev',
    stack: ['ReactJS', 'NextJS', 'TypeScript', 'i18next'],
    description: <Trans>AblinDevSmallDescription</Trans>,
    github: 'https://github.com/ablin42/ablin42',
    link: '#',
  },
  {
    name: 'Airdrop Claim',
    stack: ['JavaScript'],
    description: <Trans>AirdropSmallDescription</Trans>,
    github: 'https://github.com/ablin42/generic-airdrop-claim',
    link: '#',
  },
];
